- tag: test_list_plugin
  plugin: test_list_plugins
  domain:
    - localhost
  host:
    - machine;machine
  sources:
    param1:
      series: 
        - load.load
      cf: AVERAGE
      start: "-1days"
      end: "-5minutes"
      resolution: null
    param2:
      series:
        - diskstats_latency.*.avgrdwait
      cf: AVERAGE
      start: "-1days"
      end: "-5minutes"
      resolution: null

- tag: fire_error_test
  is_enable: false
  plugin: fire_error
  host:
    - machine;machine
  sources:
    - series:
        - load.load

- tag: fire_warning_test
  is_enable: false
  plugin: fire_warning
  host:
    - machine;machine
  sources:
    - series:
        - load.load

- tag: fire_warning_test2
  is_enable: false
  plugin: fire_warning
  host:
    - machine;machine
  sources:
    - series:
        - load.load
